# pages/export.py

import io
import zipfile
import streamlit as st
from data_store import EXPORT_CSV, TRANSCRIPTIONS_DIR, rebuild_csv, list_cards

def render():
    st.title("Export Archive Data")
    st.caption("Download your processed metadata and transcribed JSON files for external database integration or archival backup.")

    st.divider()

    # Ensure the CSV is up to date before offering downloads
    rebuild_csv()

    col1, col2 = st.columns(2, gap="large")

    with col1:
        st.subheader("Master Database (CSV)")
        st.write("Download the complete relational database containing all reviewed documents, bilingual translations, and extracted metadata.")
        
        if EXPORT_CSV.exists():
            with open(EXPORT_CSV, "rb") as f:
                st.download_button(
                    label="Download metadata.csv",
                    data=f,
                    file_name="antiquities_service_metadata.csv",
                    mime="text/csv",
                    type="primary",
                    use_container_width=True
                )
        else:
            st.warning("No metadata available. Review documents to generate the database.")

    with col2:
        st.subheader("Raw Transcriptions (ZIP)")
        st.write("Download an archive of all individual JSON files generated by the Gemini pipeline.")
        
        # Build ZIP file in memory
        json_files = list(TRANSCRIPTIONS_DIR.glob("*.json"))
        if json_files:
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
                for json_path in json_files:
                    zip_file.write(json_path, arcname=json_path.name)
            
            st.download_button(
                label=f"Download {len(json_files)} JSON files (ZIP)",
                data=zip_buffer.getvalue(),
                file_name="antiquities_service_transcriptions.zip",
                mime="application/zip",
                use_container_width=True
            )
        else:
            st.warning("No transcriptions available to export.")

    st.divider()
    
    st.subheader("Export Statistics")
    cards = list_cards()
    reviewed_count = sum(1 for c in cards if c["status"] in ["reviewed", "flagged"])
    st.metric("Total Exportable Records", reviewed_count)
